### ISSUE TITLE
Documentation is not uptodate?

### ISSUE THREAD

**Issue by johanhammar** [BESTSELLER/backstage-plugin-harbor#175]
It seems that EntityHarborContent and EntityHarborWidgetCard is not available anymore?

**Comment by wrighbr** [comment]
created PR #176 to update the doco

**Comment by johanhammar** [comment]
Oops I'm too slow. But there are some other things that must be updated like the imports

import {
EntityHarborContent,
EntityHarborWidgetCard,
isHarborAvailable,
} from '@bestsellerit/backstage-plugin-harbor';
