### ISSUE TITLE
I don't think you meant for this to be included in the project.

### ISSUE THREAD

**Issue by t3hprofit** [BESTSELLER/backstage-plugin-harbor#193]
https://github.com/BESTSELLER/backstage-plugin-harbor/blob/56069c378de93a918a9a4204e2b5e9bd22b81ff7/app-config.yaml#L2

**Comment by Gaardsholt** [comment]
As we are no longer using Harbor, we will now archive this repo.
We would love to donate the project to someone else, so if anyone wanna take over the project they can contact us on EngineeringServices@bestseller.com
