### ISSUE TITLE
EntityHarborContent is expecting a required prop entity

### ISSUE THREAD

**Issue by arjunspanicker** [BESTSELLER/backstage-plugin-harbor#7]
`EntityHarborContent ` is expecting a required entity prop which is not mentioned in readme and the
 app is crashing on passing the entity from EntityPage.tsx
Also the widget component is giving an error 
` Cannot read property 'severity' of undefined type=errorHandler stack=TypeError: Cannot read property 'severity' of undefined`

**Comment by Andrei-Predoiu** [comment]
Should be fixed soon, we haven't looked at this one in a while
