### ISSUE TITLE
Learn More link is not encoded correctly when having multi-level repos

### ISSUE THREAD

**Issue by 4integration** [BESTSELLER/backstage-plugin-harbor#79]
When having images with multi level repos lite `<project>/<team>/<image>` the hyperlink för "Learn More" is
`https://harbor.company.net/harbor/projects/<project-id>/repositories/team/image` but the correct link should encode all slashes in repository with `%2F`
`https://harbor.company.net/harbor/projects/<project-id>/repositories/team%2Fimage`

When even deeper path for `<project>/<team>/<subteam>/<image>` it should be
`https://harbor.company.net/harbor/projects/<project-id>/repositories/team%2Fsubteam%2Fimage`

**Comment by johanhammar** [comment]
This should be fixed by https://github.com/BESTSELLER/backstage-plugin-harbor-backend/pull/7 in the https://github.com/BESTSELLER/backstage-plugin-harbor-backend repo

**Comment by johanhammar** [comment]
@4integration , fixed by BESTSELLER/backstage-plugin-harbor-backend#7

Please close 👍
